language: node_js
node_js:
   - "0.10"
addons:
  postgresql: "9.3"
before_install:
 - gem install compass
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
  - grunt
notifications:
  email: false
